defaults: &defaults
  docker:
    - image: circleci/python:3.5
  working_directory: ~/accession

version: 2
jobs:
  run_tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: configure auth credentials
          command: echo $GCP_key > /home/circleci/encode-processing-283326aece3d.json
      - run:
          name: install dependencies
          command: |
            sudo pip3 install pytest
            sudo pip3 install requests
            sudo pip3 install encode_utils==2.5.0
            sudo pip3 install google-cloud-storage
      - run:
          name: run tests
          command: |
            python3 -m pytest

workflows:
  version: 2
  build_workflow:
    jobs:
      - run_tests