resources:
  - name: accession
    type: compute.v1.instance
    properties:
      zone: us-west1-a
      machineType: zones/us-west1-a/machineTypes/n1-standard-2
      disks:
      - deviceName: boot
        type: PERSISTENT
        boot: true
        autoDelete: true
        initializeParams:
          sourceImage: projects/debian-cloud/global/images/family/debian-9
      networkInterfaces:
      - network: global/networks/default
      tags:
        accession-remote-caper
